server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: SERVICE-REGISTRY
  zipkin:
    base-url: http://localhost:9411/